### ISSUE TITLE
Please convert all examples and tutorials into vanilla ES6 

### ISSUE THREAD

**Issue by tpisto** [bcherny/undux#18]
For this kind of generic library it's not good to use some marginal syntax. I think one should instead use vanilla ES6 and then people who use X to JS converters can easily adjust the code into their favourite compiler.

**Comment by bcherny** [comment]
Thanks for the suggestion @tpisto! I'll keep it in mind, but one of the really big benefits of Undux vs. Redux or Flux is that Undux is completely type safe. Because that's such a big deal, I wanted to show it off.

When I get a demo site up, I'll make a little TypeScript-Flow-ES6-ES5 slider to choose which mode you want to see examples in.
