### ISSUE TITLE
Question: Is there simple way to cancel the value update when some condition met?

### ISSUE THREAD

**Issue by tpisto** [bcherny/undux#19]

**Comment by bcherny** [comment]
Hi @tpisto! There's no way to cancel and update - that's by design. You can, however, use an [effect](https://github.com/bcherny/undux#effects) to listen on an update to update another property in response - that's where you can put fancy conditional logic.

The idea behind that design decision is that:

1. Updates should always succeed, so we don't need to introduce a notion of transactions
2. Updates should be listened on, but not intercepted and transformed. Interception is messy, and makes it non-obvious what will happen when you issue an update command: will it succeed? Will it fail? Will it succeed but its data will be transformed by some middleware? Additionally, what if you intercept an update and want to run an async check on it - should subsequent updates be queued up? Should there be a way to declare dependencies between updates?

Hopefully that makes sense. What's your use case? I'm happy to help figure out a clean way to express your logic with Undux.

And if all else fails, you can always use action creators and the [thunk pattern](https://github.com/gaearon/redux-thunk) with Undux, though it's not encouraged.

**Comment by tpisto** [comment]
Thank you for your quick reply! I have played with your library today and it looks and feels absolutely wonderful. Coming from Redux and Redux Saga background I would just simply want to respond to button clicks. I really like to keep the Api fetches away from components, and in redux it's easy with actions. 

I don't know what would be best pattern with Undux for that. My current solution: I have now created variable "fetchDataX" and with buttonClick I set that variable to from "false" to "true". And I have subscribed to that variable to fetch my data. I thought that would be nice just to cancel the value change to respond multiple button clicks.

I'm currently using   .filter(shouldFetch => shouldFetch === true)  and then in subscribe I     store.set('fetchDataX')(false). I don't know if that's the best pattern...

Again, thank you for your library and support!

**Comment by bcherny** [comment]
> I have played with your library today and it looks and feels absolutely wonderful.

Thanks :)

> I thought that would be nice just to cancel the value change to respond multiple button clicks.

To specify this a bit better, do you mean you want to cancel an in-flight network request when the user presses twice, or wait some amount of time after a click but before fetching to make sure the user didn't press twice, or something else?

**Comment by bcherny** [comment]
At a high level, I think you have a few options. The simplest is to not use Undux for this, and just call a function to fetch your data:

```ts
<button onClick={fetchData} />

async function fetchData() {
  store.set('result')(await fetchJSON(...))
}
```

If you want to ignore multiple clicks issues one after another quickly, you can use an Observable. Something like this:

```ts
let subject = new Rx.Subject

<button onClick={subject.onNext} />

subject
  .bufferTime(300)
  .filter(_ => _ % 2)
  .subscribe(fetchData)
```

And if you want, you can use Undux for this, though you introduce a throwaway property to your store (the thing you're trying to model is a *transition* between states, not a *state*):

```ts
<button onClick={store.set('triggerFetch')()} />

store
  .on('triggerFetch')
  .bufferTime(300)
  .filter(_ => _ % 2)
  .subscribe(fetchData)
```

This last use case might break if we ever decide to dedupe .set calls in the future (like we already do for React re-renders).

Conceptually, Undux models states, while Redux models Transitions between states. My hunch is that the majority of Redux uses cases actually care about states, not transitions, so Undux's way of looking at it is more natural. If it turns out that transitions are a more common use case (as they are in your case), I may add an API to repurpose an Undux store as a raw emitter. Something like:

```ts
store.emit('triggerFetch')

store
  .on('triggerFetch')
  .bufferTime(300)
  .filter(_ => _ % 2)
  .subscribe(fetchData)
```

Hope that helps - let me know what you end up going with, or if you come up with another way to model this!

**Comment by erixtekila** [comment]
Hi @bcherny 

This `emit()` new method to handle state transitions would be a nice and lightweight addition.
Do you see any trouble to include it ?

Thanks.

**Comment by bcherny** [comment]
@erixtekila I’d like to avoid making the API more complex if possible. Would a regular function work for your use case?

    function myAction(data) {
      let result = doSomething(data)
      return result.something
    }

    store.set('key')(myAction(store))

**Comment by erixtekila** [comment]
Yes for sure.
That was my fallback technic.

BTW, I was searching for something more generic…
In this sense, the `emit()` was appealing.

Thanks for all, and mostly for your good vibes lib' !

**Comment by erixtekila** [comment]
You'd write all those design philosophies in the documentation.
There are really clever, but not mainstream.
