### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by ghost** [bcherny/undux#40]
Trying to run simple hello world. Here are my files:
```
// store.js
import { connect, createStore } from 'undux'

// Create a store with an initial value.
let store = createStore({
  today: new Date,
  users: []
})

export let withStore  = connect(store)
```
```
// App.js
import React, { Component } from 'react';
import { withStore  } from './Store'

// Update the component when the store updates.
let App = withStore (
  class extends React.Component {
    render() {
      let store = this.props.store;
      return (<div>
        Hello! Today is {store.get('today')}
        <button onClick={() => store.set('today')(new Date)}>Update Date</button>
      </div>)
    }
  }
)

export default App;
```
```
// index.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
 
ReactDOM.render(<App />, document.getElementById('root'));
```

This is the error I get:

> Objects are not valid as a React child (found: Sat Jun 02 2018 16:37:40 GMT+0400 (Georgian Standard Time)). If you meant to render a collection of children, use an array instead.
>     in div (at App.js:9)
>     in _class (created by withStore(_class))
>     in withStore(_class) (at index.js:5)
> 

Any idea why?

**Comment by bcherny** [comment]
Hey @giorgim! Sorry about that, it's a bug in the docs :) The problem is not related to Undux - it's that React can't render JavaScript `Date` objects.

I've updated the documentation, and added a [live playground link](https://stackblitz.com/edit/js-gwo2c3?file=MyStore.js).

**Comment by giorgim** [comment]
@bcherny Are the updates async? Because this code logs 0 after first click.

```
store.set('clickCount')(store.get('clickCount') + 1)
console.log(store.get('clickCount'))
```

btw. good idea to have state management library with easy to use API.

**Comment by bcherny** [comment]
@giorgim Undux updates are synchronous, and are guaranteed to succeed in the same tick. What you're looking at is a React behavior. The value will update the next time that React re-renders your component, which will happen in the next tick.

**Comment by bcherny** [comment]
Yeah, it’s a fair point that needs better documentation. I’m experimenting a bit with other options. We could make the update more “synchronous”, but it would come at the expense of store being immutable. My hunch is that the trade off is worth it. Will keep you posted!

**Comment by giorgim** [comment]
@bcherny Yeah then doc has to say it.
I will give you some feedback in general if you don't mind about state management libraries in general in my opinion, maybe you can some up with a better one ;) (or someone else).

1. Yeah if you make it truly synchronous it could be good, because that is one of the shortcomings
of setState (well at least many consider so). But I am not sure if you can make setState synchronous in general, as Dan abramov pointed why setState can't be synchronous here: https://github.com/facebook/react/issues/11527#issuecomment-360199710
Not sure if it applies to your case.

I praised your effort to have a state management library with easy to use API.
For example I liked mobx because it is more intuitive and more OOP, but it also
has some subtleties, e.g. https://mobx.js.org/best/react.html, after reading
that post I remember I was still not 100% sure how it worked.

So in the end I think what we lack currently is a state management library that
is truly easy to use, and easy to reason about. 

Just some my thoughts, good luck.
